### ISSUE TITLE
No fileType when uploading an apk

### ISSUE THREAD

**Issue by backmeupplz** [shr3jn/fastlane-plugin-huawei_appgallery_connect#15]
Receiving this error:

`{"ret"=>{"code"=>203489281, "msg"=>"[AppGalleryConnectPublishService]updateAppFileInfo.arg3.fileType: must not be null"}}`

Kinda weird because fileType is set to 5 in the request 🤔

It's happening on the `Saving app information` step

**Comment by backmeupplz** [comment]
https://github.com/arnekaiser/fastlane-plugin-huawei_appgallery works though, so I use it to upload an apk and then `fastlane-plugin-huawei_appgallery_connect` to submit it for review :)

**Comment by leo-pedidosya** [comment]
Hi we are facing the same issue

**Comment by shr3jn** [comment]
v1.0.11 released

**Comment by rimzici** [comment]
Still occurring in v1.0.12

```

**Comment by leo-pedidosya** [comment]
Yes, I have just checked and still occurring with latest version (1.0.12)

**Comment by shr3jn** [comment]
Ok will sort this out tomorrow.

**Comment by leo-pedidosya** [comment]
Thanks!
Just to help in any way the issue is that when using this  [API](https://connect-api.cloud.huawei.com/api/publish/v2/app-submit) there's no fileType attribute to send as per the documentation [here](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-submit_v2).

**Comment by shr3jn** [comment]
Issue resolved on v1.0.13 @leo-pedidosya @rimzici

**Comment by rimzici** [comment]
Can confirm! Thanks @shr3jn
